version: '3.8'
services:
  mongo1:
    image: mongo
    container_name: mongo1
    volumes:
      - mongo1data:/data/db
      - ./mongodb-keyfile:/etc/mongo/mongodb-keyfile
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=512project
    command: mongod --replSet myreplset --bind_ip_all --keyFile /etc/mongo/mongodb-keyfile
    ports:
      - "27018:27017"

  mongo2:
    image: mongo
    container_name: mongo2
    volumes:
      - mongo2data:/data/db
      - ./mongodb-keyfile:/etc/mongo/mongodb-keyfile
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=512project
    command: mongod --replSet myreplset --bind_ip_all --keyFile /etc/mongo/mongodb-keyfile
    ports:
      - "27019:27017"

  mongo3:
    image: mongo
    container_name: mongo3
    volumes:
      - mongo3data:/data/db
      - ./mongodb-keyfile:/etc/mongo/mongodb-keyfile
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=512project
    command: mongod --replSet myreplset --bind_ip_all --keyFile /etc/mongo/mongodb-keyfile
    ports:
      - "27020:27017"

volumes:
  mongo1data:
  mongo2data:
  mongo3data:
